FROM python:3.11-alpine

WORKDIR /ce-backend

COPY . .

RUN pip install -r requirements.txt

CMD ["python", "manage.py", "runsslserver", "0.0.0.0:7000", "--cert", "certificate.pem", "--key", "key.pem"]
